[workspace]
resolver = "2"
members = [
  "crates/wasmbox-core",
  "crates/wasmbox-cli",
  "crates/wasmbox-ui",
  "examples/guest-echo",
  "examples/host-run",
  "crates/wat-compile-scenarios",
  "examples/scenario-tool-handler",
  "examples/scenario-tool-handler/guest",
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"

[profile.release]
opt-level = 3
